### ISSUE TITLE
关盖睡眠后,开盖黑屏

### ISSUE THREAD

**Issue by Wjcccccccccc** [HeartAndSoul001/my-EFI-for-x1-carbon-5th#1]
如题,睡眠后开盖黑屏,卡很久后重新进入引导界面,显示出现问题重新启动.
但是关盖后,立马开盖能正常打开.
请问兄弟有这个问题吗?

**Comment by HeartAndSoul001** [comment]
没有，我的都挺正常的，我怀疑你那个是RTC的问题

**Comment by Wjcccccccccc** [comment]
以下是我的config,plist(改成txt后缀了上传了).
[config.txt](https://github.com/HeartAndSoul001/my-EFI-for-x1-carbon-5th/files/5720793/config.txt)

我只加了三码,和dw1560的驱动,其他都是用跟你一样的.
机器型号Thinkpad x1c5 跟你一模一样.
我查了说是HibernationFixup的问题,但是你的kext已经是最新的了...
请问下能否详细说下rtc的什么问题,获取看下我的config,plist有什么问题呀,感谢!

**Comment by HeartAndSoul001** [comment]
这个没用，你

> 如题,睡眠后开盖黑屏,卡很久后重新进入引导界面,显示出现问题重新启动.
> 但是关盖后,立马开盖能正常打开.
> 请问兄弟有这个问题吗?

出现问题重新启动应该会弹出问题信息的，发来看看呢？

**Comment by Wjcccccccccc** [comment]
panic(cpu 3 caller 0xffffff8004383d06): nvme: "Fatal error occurred. CSTS=0xffffffff US[1]=0x0 US[0]=0xea VID=0x8086 DID=0xf1a5
. FW Revision=123P\n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-557.60.1/Common/IONVMeController.cpp:5472
Backtrace (CPU 3), Frame : Return Address
0xffffffa060bdb990 : 0xffffff8001cb9aed 
0xffffffa060bdb9e0 : 0xffffff8001dfc6e3 
0xffffffa060bdba20 : 0xffffff8001decd1a 
0xffffffa060bdba70 : 0xffffff8001c5ea2f 
0xffffffa060bdba90 : 0xffffff8001cb938d 
0xffffffa060bdbbb0 : 0xffffff8001cb9678 
0xffffffa060bdbc20 : 0xffffff80024be3ca 
0xffffffa060bdbc90 : 0xffffff8004383d06 
0xffffffa060bdbcb0 : 0xffffff8004368427 
0xffffffa060bdbe10 : 0xffffff800436c2ff 
0xffffffa060bdbe40 : 0xffffff8004368153 
0xffffffa060bdbe80 : 0xffffff8001cfe6b5 
0xffffffa060bdbef0 : 0xffffff8001cff5c4 
0xffffffa060bdbfa0 : 0xffffff8001c5e13e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[008D1169-B6FD-39ED-9033-C67AC409031C]@0xffffff8004361000->0xffffff800438afff
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[E4DF1D8B-0DA9-33A8-A7B6-17DCA1678FC0]@0xffffff8003059000->0xffffff8003062fff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[9BA70327-883F-3E4F-960A-14203BB191FD]@0xffffff8003200000->0xffffff8003214fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[D0F1BFB8-C28E-3E70-891B-73B783189394]@0xffffff800462c000->0xffffff8004653fff
            dependency: com.apple.iokit.IOReportFamily(47)[3A404946-7B6B-371A-A7B5-96E25F6F449D]@0xffffff8004662000->0xffffff8004664fff
            dependency: com.apple.iokit.IOStorageFamily(2.1)[AA8F8B9D-BA6E-3EBB-8195-4792042ADF71]@0xffffff800474c000->0xffffff800475dfff

Process name corresponding to current thread: kernel_task

Mac OS version:
20C69

Kernel version:
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Kernel UUID: 82E2050C-5936-3D24-AD3B-EC4EC5C09E11
KernelCache slide: 0x0000000001a00000
KernelCache base:  0xffffff8001c00000
Kernel slide:      0x0000000001a10000
Kernel text base:  0xffffff8001c10000
__HIB  text base: 0xffffff8001b00000
System model name: MacBookPro14,2 (Mac-CAD6701F7CEA0921)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 59821191729
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000000ded9ef4f0
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x000000182323407c 0x0000000000000000
last started kext at 24261395892: >AudioAUUC	1.70 (addr 0xffffff7fa2183000, size 12288)
loaded kexts:
me.kishorprins.VoodooInput	1.0.9
as.acidanthera.BrcmPatchRAM3	2.5.4
as.acidanthera.voodoo.driver.PS2Mouse	2.1.9
as.acidanthera.voodoo.driver.PS2Trackpad	2.1.9
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.9
as.acidanthera.mieze.!IMausi	1.0.4
ru.joedm.SMCSuperIO	1.1.9
as.lvs1974.RTCMemoryFixup	1.0.7
as.acidanthera.voodoo.driver.PS2!C	2.1.9
as.vit9696.SMCProcessor	1.1.9
as.lvs1974.HibernationFixup	1.3.8
org.acidanthera.NVMeFix	1.0.4
org.vanilla.driver.CPUFriend	1.2.2
as.vit9696.!AALC	1.5.5
as.vit9696.WhateverGreen	1.4.5
ru.usrsse2.SMCLightSensor	1.1.9
ru.usrsse2.SMCBatteryManager	1.1.9
as.vit9696.VirtualSMC	1.1.9
as.acidanthera.BrcmFirmwareStore	2.5.4
as.lvs1974.AirportBrcmFixup	2.1.2
as.vit9696.Lilu	1.5.0
>AudioAUUC	1.70
>AGPM	119
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
@fileutil	20.036.15
>!AUpstreamUserClient	3.6.8
>!AHDAHardwareConfigDriver	283.15
>!AGraphicsDevicePolicy	6.2.2
>!AHDA	283.15
@AGDCPluginDisplayMetrics	6.2.2
>!A!IKBLGraphics	16.0.1
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
>usb.!UUserHCI	1
>!A!IKBLGraphicsFramebuffer	16.0.1
|IO!BSerialManager	8.0.2f9
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!ADiskImages2	1
>ACPI_SMC_PlatformPlugin	1.0.0
>AGDCBacklightControl	6.2.2
>!ABacklight	180.3
>!AGFXHDA	100.1.431
>!A!ISlowAdaptiveClocking	4.0.0
>!AFIVRDriver	4.1.0
>!A!IPCHPMC	2.0.1
>!ASMCLMU	212
>!AMCCSControl	1.14
>!ATopCaseHIDEventDriver	4020.6
>!AFileSystemDriver	3.0.1
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@filesystems.apfs	1677.60.23
>!ASmartBatteryManager	161.0.0
>AirPort.BrcmNIC	1400.1.1
@private.KextAudit	1.0
>!ARTC	2.0
>!AHPET	1.8
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
>!AGraphicsControl	6.2.2
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
|IOAccelerator!F2	439.52
|IOSerial!F	11
|IOAVB!F	900.12
@!AGPUWrangler	6.2.2
>IOPlatformPluginLegacy	1.0.0
>X86PlatformPlugin	1.0.0
>usb.IOUSBHostHIDDevice	1.2
@!AGraphicsDeviceControl	6.2.2
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
>!ABacklightExpert	1.1.0
>!AHDA!C	283.15
|IOHDA!F	283.15
|IONDRVSupport	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!ASMBusPCI	1.0.14d1
|IOGraphics!F	585
>!ASMBus!C	1.0.18d1
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
>!AHS!BDriver	4020.6
>IO!BHIDDriver	8.0.2f9
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	8.0.2f9
|IO!BHost!CUSBTransport	8.0.2f9
|IO!BHost!CTransport	8.0.2f9
>!UMergeNub	900.4.2
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
>!AXsanScheme	3
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
|IONVMe!F	2.1.0
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
>!A!ILpssGspi	3.0.60
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOSMBus!F	1.1
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.2f9
|IOReport!F	47
|IO!BPacketLogger	8.0.2f9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1

**Comment by HeartAndSoul001** [comment]
这个报错信息一看就知道是nvme固态报错啊。我怀疑是固态扇区有问题。首先尝试把我config文件里有一个device properties的条目里硬盘的那个删掉，然后保存重启试试。如果还有问题，就自己做一个PE启动盘吧，在PE里用工具检查一下固态磁盘的扇区有没有坏的存储块。没有的话就用时间机器备份系统，然后PE里对整个硬盘彻底格式化，然后再用一个OC引导安装macOS的启动U盘从你之前备份的系统恢复过来，然后再看看还有没有这个问题。最后还不行的话，就只能换个硬盘了

**Comment by Wjcccccccccc** [comment]
硬盘也换成三星970 evo了，唤醒还是黑屏，现在我除了网卡是dw1560，其他都跟你一样了，大佬能不能帮忙分析下问题。。。
`panic(cpu 2 caller 0xffffff801116ea25): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since wake (370 seconds ago): 38, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since wake (370 seconds ago): 26, last successful checkin: 120 seconds ago

Backtrace (CPU 2), Frame : Return Address
0xffffffb09e483670 : 0xffffff800deb9aed 
0xffffffb09e4836c0 : 0xffffff800dffc6e3 
0xffffffb09e483700 : 0xffffff800dfecd1a 
0xffffffb09e483750 : 0xffffff800de5ea2f 
0xffffffb09e483770 : 0xffffff800deb938d 
0xffffffb09e483890 : 0xffffff800deb9678 
0xffffffb09e483900 : 0xffffff800e6be434 
0xffffffb09e483970 : 0xffffff801116ea25 
0xffffffb09e483980 : 0xffffff801116e678 
0xffffffb09e4839a0 : 0xffffff800e64569e 
0xffffffb09e4839f0 : 0xffffff801116dab4 
0xffffffb09e483b20 : 0xffffff800e64f86b 
0xffffffb09e483c80 : 0xffffff800dfa7d81 
0xffffffb09e483d90 : 0xffffff800debf0e7 
0xffffffb09e483e00 : 0xffffff800de95905 
0xffffffb09e483e60 : 0xffffff800dead012 
0xffffffb09e483ef0 : 0xffffff800dfd0ec3 
0xffffffb09e483fa0 : 0xffffff800de5f216 
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[7AE04EA4-D026-39A0-B2D5-5C9E4EE72967]@0xffffff801116d000->0xffffff801116efff

Process name corresponding to current thread: watchdogd
Boot args: vsmcgen=1 

Mac OS version:
20C69

Kernel version:
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Kernel UUID: 82E2050C-5936-3D24-AD3B-EC4EC5C09E11
KernelCache slide: 0x000000000dc00000
KernelCache base:  0xffffff800de00000
Kernel slide:      0x000000000dc10000
Kernel text base:  0xffffff800de10000
__HIB  text base: 0xffffff800dd00000
System model name: MacBookPro14,2 (Mac-CAD6701F7CEA0921)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 592670695526
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x00000089fded253e
  Sleep   : 0x00000032fcfc235f 0x0000001063928424 0x0000000000000000
  Wake    : 0x0000003300121681 0x000000009858be68 0x00000032fe17ad5a
last started kext at 480169303852: >usb.!UUserHCI	1 (addr 0xffffff7fae79d000, size 98304)
last stopped kext at 290302673999: ru.joedm.SMCSuperIO	1.1.9 (addr 0xffffff8011f03000, size 77824)
loaded kexts:
me.kishorprins.VoodooInput	1.0.9
as.acidanthera.BrcmPatchRAM3	2.5.4
as.acidanthera.voodoo.driver.PS2Trackpad	2.1.9
as.acidanthera.voodoo.driver.PS2Keyboard	2.1.9
ru.joedm.SMCSuperIO	1.1.9
as.acidanthera.mieze.!IMausi	1.0.4
as.lvs1974.RTCMemoryFixup	1.0.7
as.acidanthera.voodoo.driver.PS2!C	2.1.9
as.vit9696.SMCProcessor	1.1.9
as.lvs1974.HibernationFixup	1.3.8
org.acidanthera.NVMeFix	1.0.4
org.vanilla.driver.CPUFriend	1.2.2
as.vit9696.!AALC	1.5.5
as.vit9696.WhateverGreen	1.4.5
ru.usrsse2.SMCLightSensor	1.1.9
ru.usrsse2.SMCBatteryManager	1.1.9
as.vit9696.VirtualSMC	1.1.9
as.acidanthera.BrcmFirmwareStore	2.5.4
as.lvs1974.AirportBrcmFixup	2.1.2
as.vit9696.Lilu	1.5.0
>usb.!UUserHCI	1
>AudioAUUC	1.70
>!APlatformEnabler	2.7.0d0
>AGPM	119
>X86PlatformShim	1.0.0
@filesystems.autofs	3.0
>!AGraphicsDevicePolicy	6.2.2
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	6.2.2
>pmtelemetry	1
>LuaHardwareAccess	1.0.16
|IOUserEthernet	1.0.1
|IO!BSerialManager	8.0.2f9
>!AUpstreamUserClient	3.6.8
>!AHDA	283.15
@Dont_Steal_Mac_OS_X	7.0.0
>!AHV	1
>!A!IKBLGraphics	16.0.1
>!ADiskImages2	1
>!A!IKBLGraphicsFramebuffer	16.0.1
>!ABacklight	180.3
>!AMCCSControl	1.14
>!A!ISlowAdaptiveClocking	4.0.0
>!A!IPCHPMC	2.0.1
>!ASMCLMU	212
>!ATopCaseHIDEventDriver	4020.6
@filesystems.tmpfs	1
@filesystems.hfs.kext	556.60.1
@BootCache	40
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
>!ASmartBatteryManager	161.0.0
@private.KextAudit	1.0
@filesystems.apfs	1677.60.23
>AirPort.BrcmNIC	1400.1.1
>!ARTC	2.0
>!AHPET	1.8
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
@!ASystemPolicy	2.0.0
@nke.applicationfirewall	310
|IOKitRegistryCompatibility	1
|EndpointSecurity	1
@kext.triggers	1.0
>!AGraphicsControl	6.2.2
|IOSerial!F	11
|IOAVB!F	900.12
>DspFuncLib	283.15
@kext.OSvKernDSPLib	529
>!ASMBusPCI	1.0.14d1
|IOAccelerator!F2	439.52
>!ABacklightExpert	1.1.0
>!AHDA!C	283.15
|IOHDA!F	283.15
@plugin.IOgPTPPlugin	900.11
|IOEthernetAVB!C	1.1.0
|IONDRVSupport	585
|IOAudio!F	300.6.1
@vecLib.kext	1.2.0
>!ASMBus!C	1.0.18d1
@!AGPUWrangler	6.2.2
@!AGraphicsDeviceControl	6.2.2
|IOSlowAdaptiveClocking!F	1.0.0
|IOGraphics!F	585
>X86PlatformPlugin	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!AHS!BDriver	4020.6
>IO!BHIDDriver	8.0.2f9
>!AActuatorDriver	4400.28
>!AMultitouchDriver	4400.28
>!AInputDeviceSupport	4400.35
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
|Broadcom!BHost!CUSBTransport	8.0.2f9
|IO!BHost!CUSBTransport	8.0.2f9
|IO!BHost!CTransport	8.0.2f9
>!UMergeNub	900.4.2
>!ABSDKextStarter	3
|IOSurface	289.3
@filesystems.hfs.encodings.kext	1
|IOUSB!F	900.4.2
|IONVMe!F	2.1.0
|IO80211!F	1200.12.2b1
|IOSkywalk!F	1
>mDNSOffloadUserClient	1.0.1b8
>corecapture	1.0.4
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
|IOHID!F	2.0.0
$!AImage4	3.0.0
|IOSMBus!F	1.1
|IOTimeSync!F	900.11
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	8.0.2f9
|IOReport!F	47
|IO!BPacketLogger	8.0.2f9
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
|CoreAnalytics!F	1
>!ASSE	1.0
>!AKeyStore	2
>!UTDM	511.60.2
|IOUSBMass!SDriver	184.40.6
|IOSCSIBlockCommandsDevice	436.40.6
|IO!S!F	2.1
|IOSCSIArchitectureModel!F	436.40.6
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!ACredentialManager	1.0
>KernelRelayHost	1
|IOUSBHost!F	1.2
>!UHostMergeProperties	1.2
>usb.!UCommon	1.0
>!ABusPower!C	1.0
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AACPIPlatform	6.1
>!ASMC	3.1.9
|IOPCI!F	2.9
|IOACPI!F	1.4
>watchdog	1
@kec.pthread	1
@kec.corecrypto	11.1
@kec.Libm	1


`

**Comment by HeartAndSoul001** [comment]
你的EFI文件发到邮箱  347596212@qq.com，我看看

**Comment by HeartAndSoul001** [comment]
还需提供以下信息：
1. 出问题时是否有外接设备？如果有，什么接口拓展的
2. bios里相关选项有没有设置过？如果有，设置了哪些

**Comment by HeartAndSoul001** [comment]
可以直接加我qq吧，运气好能帮你解决，不然我也没法了

**Comment by Wjcccccccccc** [comment]
感谢楼主的帮助，问题解决了，开启hidpi后，睡眠唤醒一切正常。
https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md

之前intel硬盘总是切换应用卡顿，换了三星970 evo后没有出现了。
现在就是dw1560的wifi信道有些不支持，可能需要调整路由器的输出信道，然后就是蓝牙也有部分设备不识别，鼠标卡顿。
至此我的黑苹果也算接近完美了，再次感谢楼主！

**Comment by HeartAndSoul001** [comment]
> 感谢楼主的帮助，问题解决了，开启hidpi后，睡眠唤醒一切正常。
> https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md
> 
> 之前intel硬盘总是切换应用卡顿，换了三星970 evo后没有出现了。
> 现在就是dw1560的wifi信道有些不支持，可能需要调整路由器的输出信道，然后就是蓝牙也有部分设备不识别，鼠标卡顿。
> 至此我的黑苹果也算接近完美了，再次感谢楼主！

我也没帮上什么忙，是你自己解决了。我也是第一次遇到hidpi也会影响唤醒黑屏的问题，学习到了。我最近又改了一下亮度快捷键的东西，少了一些ssdt和patch，多了个brightness.kext

**Comment by Wjcccccccccc** [comment]
> > 感谢楼主的帮助，问题解决了，开启hidpi后，睡眠唤醒一切正常。
> > https://github.com/xzhih/one-key-hidpi/blob/master/README-zh.md
> > 之前intel硬盘总是切换应用卡顿，换了三星970 evo后没有出现了。
> > 现在就是dw1560的wifi信道有些不支持，可能需要调整路由器的输出信道，然后就是蓝牙也有部分设备不识别，鼠标卡顿。
> > 至此我的黑苹果也算接近完美了，再次感谢楼主！
> 
> 我也没帮上什么忙，是你自己解决了。我也是第一次遇到hidpi也会影响唤醒黑屏的问题，学习到了。我最近又改了一下亮度快捷键的东西，少了一些ssdt和patch，多了个brightness.kext

楼主有啥更新有空可以同步下github呀，我现在机型跟你基本一致了。😊
