### ISSUE TITLE
合盖开盖唤醒黑屏

### ISSUE THREAD

**Issue by matoung** [HeartAndSoul001/my-EFI-for-x1-carbon-5th#2]
你好，同款x1使用这个efi后成功安装big sur，整体正常，比较大的问题是合盖休眠后开盖无法唤醒，
请帮忙看下需要排查哪些 多谢 @HeartAndSoul001

**Comment by HeartAndSoul001** [comment]
如果EFI文件是整体替换的，需要排查一下BIOS设置。有可能是核显的注入参数有关
