### ISSUE TITLE
蓝牙无法识别

### ISSUE THREAD

**Issue by pandada1999** [HeartAndSoul001/my-EFI-for-x1-carbon-5th#3]
你好，我和你的机器型号一样，目前用的cs2网卡，big sur 11.6 。
请问网卡正常使用需要修改BIOS白名单吗，我试过dw1820a和cs2两张网卡，都是WiFi可以用但是没有蓝牙模块

**Comment by HeartAndSoul001** [comment]
我的蓝牙模块一直都是好的，也没用什么驱动。从macos catalina开始一直好的。由于蓝牙是走的usb通道，你可以把你的usb定制一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: PandaDa ***@***.***&gt;
发送时间: 2021年11月24日 20:46
收件人: HeartAndSoul001/my-EFI-for-x1-carbon-5th ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [HeartAndSoul001/my-EFI-for-x1-carbon-5th] 蓝牙无法识别 (Issue #3)





 
你好，我和你的机器型号一样，目前用的cs2网卡，big sur 11.6 。
 请问网卡正常使用需要修改BIOS白名单吗，我试过dw1820a和cs2两张网卡，都是WiFi可以用但是没有蓝牙模块
