### ISSUE TITLE
我的也是x1c2017 i7-7600u 16G 1T盘，不是2k屏，网卡没换

### ISSUE THREAD

**Issue by sair0117** [HeartAndSoul001/my-EFI-for-x1-carbon-5th#5]
用你的efi，去掉网卡后，无法启动 报zero错误，把config.list里面的安全驱动改成disable后到选项界面，但是看到启动盘，只能看到恢复ram 重启和关机看不到，但是tab可以选择，或者鼠标都可以点击，奇怪的是我bios的安全启动默认是关闭的，反正如何都找不到mac启动，win盘也找不到，不明白什么问题，我现在bios恢复默认了，用之前找的efi一直运行着，对了，我一直没填3码，现在系统bios是1.45 mac是mojave

**Comment by HeartAndSoul001** [comment]
请按照黑果小兵提示https://blog.daliansky.net/macOS-Monterey-12.1-21C52-Release-version-with-OC-0.7.6-CLOVER-5143-and-FirPE-original-image.html#more检查所有的bios，然后把misc中security的有一个选项改一下，设置为扫描所有磁盘分区，具体哪个我忘记了，用occ打开找一下就知道了。实在不行就把我的acpi，device properties，kext，uefi driver等移过去，其他的设置还用你原来的就行

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sair0117 ***@***.***&gt;
发送时间: 2022年1月27日 23:18
收件人: HeartAndSoul001/my-EFI-for-x1-carbon-5th ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [HeartAndSoul001/my-EFI-for-x1-carbon-5th] 我的也是x1c2017 i7-7600u 16G 1T盘，不是2k屏，网卡没换 (Issue #5)





 
用你的efi，去掉网卡后，无法启动 报zero错误，把config.list里面的安全驱动改成disable后到选项界面，但是看到启动盘，只能看到恢复ram 重启和关机看不到，但是tab可以选择，或者鼠标都可以点击，奇怪的是我bios的安全启动默认是关闭的，反正如何都找不到mac启动，win盘也找不到，不明白什么问题，我现在bios恢复默认了，用之前找的efi一直运行着，对了，我一直没填3码，现在系统bios是1.45 mac是mojave
